name: Prerelease from Tag

on:
  push:
    tags:
      - "[12].[0-9]+.[0-9]+-*"

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          allow_override: true
          prerelease: true
