name: Release from Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: "Create Github Release"
    runs-on: ubuntu-latest

    steps:
      - name: Check Tag
        run: |
          if [[ $GITHUB_REF =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
            echo "::debug::This is a Release"
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          else 
            echo "::debug::This is a Pre-Release"; 
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi;

      - name: Prerelease
        uses: meeDamian/github-release@2.0

        if: env.IS_RELEASE == 'false'

        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          allow_override: true
          prerelease: true

      - name: Release
        uses: meeDamian/github-release@2.0

        if: env.IS_RELEASE == 'true'

        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          allow_override: true
